version: '3.3'
services:
    enigmatica6creative:
        container_name: enigmatica6creative
        volumes:
            - '/opt/minecraft/e6c:/data'
        restart: unless-stopped
        ports:
            - '25589:25565'
            - '8118:8123'
        image: enigmatica6:creative
        labels:
           traefik.frontend.rule: "Host:e6-map.eyemon.de,"
           traefik.enable: true
           traefik.port: 8119