version: '3.3'
services:
    skyfactory4:
        container_name: sf4
        volumes:
            - '/opt/minecraft/sf4/world:/minecraft/world'
            - '/opt/minecraft/sf4/ops.json:/minecraft/ops.json'
            - '/opt/minecraft/sf4/server.properties:/minecraft/server.properties'
            - '/opt/minecraft/sf4/whitelist.json:/minecraft/whitelist.json'
        restart: unless-stopped
        ports:
            - '25569:25565'
        image: cochief/skyfactory4
        labels:
           traefik.frontend.rule: "Host:sf4.eyemon.de,"
           traefik.enable: true