version: '3.3'
services:
    skyfactory4:
        container_name: sf4
        volumes:
            - '/opt/minecraft/sf4/world:/minecraft/world'
            - '/opt/minecraft/ops.json:/minecraft/ops.json'
            - '/opt/minecraft/server.properties:/minecraft/server.properties'
            - '/opt/minecraft/whitelist.json:/minecraft/whitelist.json'
        restart: unless-stopped
        ports:
            - '25565:25565'
        image: cochief/skyfactory4