version: '3.3'
services:
    factorio:
        ports:
            - '34197:34197/udp'
            - '27015:27015/tcp'
        volumes:
            - '/opt/factorio/server01:/factorio'
        container_name: factorio_server01
        restart: unless-stopped
        image: factoriotools/factorio
