version: '3.5'

services:
  hub:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: 1.15.2
      MEMORY: "5G"
      LEVEL_TYPE: "FLAT"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/hub/data:/data
    restart: always
  creative:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: 1.15.2
      MEMORY: "1G"
      LEVEL_TYPE: "FLAT"
      MODE: "CREATIVE"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/creative/data:/data
    restart: always
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: 1.15.2
      MEMORY: "4G"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/vanilla/data:/data
    restart: always
    ports:
      - 8123:8123
  factions:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: 1.15.2
      MEMORY: "2G"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/factions/data:/data
    restart: always
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    volumes:
      - /opt/minecraft/bungeestack/bungeecord/server:/server
    restart: always
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
