version: '3.5'

services:
  hub:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: latest
      MEMORY: "5G"
      LEVEL_TYPE: "FLAT"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/hub/data:/data
    restart: always
    networks:
      - bungeestack
  creative:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: latest
      MEMORY: "1G"
      LEVEL_TYPE: "FLAT"
      MODE: "CREATIVE"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/creative/data:/data
    restart: always
    networks:
      - bungeestack
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: latest
      MEMORY: "4G"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/vanilla/data:/data
    restart: always
    ports:
      - 8123:8123
    networks:
      - bungeestack
  whitelisted:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: latest
      MEMORY: "6G"
    command: -- nosonsole
    volumes:
      - /opt/minecraft/bungeestack/whitelisted/data:/data
    restart: always
    networks:
      - bungeestack
    #
  factions:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: latest
      MEMORY: "2G"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/factions/data:/data
    restart: always
    networks:
      - bungeestack
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      BUNGEE_JOB_ID: "lastStableBuild"
    ports:
      - 25565:25577
    volumes:
      - /opt/minecraft/bungeestack/bungeecord/server:/server
    restart: always
    networks:
      - bungeestack
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    networks:
      - bungeestack
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - bungeestack