version: '3.5'

services:
  hub:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: 1.15.2
      MEMORY: "1G"
    command: --noconsole
    volumes:
      - /opt/minecraft/bungeestack/hub/data:/data
    
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
    ports:
      - 25565:25577
    volumes:
      - /opt/minecraft/bungeestack/bungeecord/config.yml:/server/config.yml
